#!/bin/sh
CONTAINERID=gotary-test

if [ $# -gt 0 ]; then
    OPT=$1
else
    OPT=test
fi

case $OPT in
    ("kill")
        docker kill $CONTAINERID
        docker rm $CONTAINERID
        exit
        ;;
esac

if ! docker ps | grep -q $CONTAINERID; then
        echo "no running docker found, running new one"
        docker run  -p 5432:5432 -p 5150:5150 -d -ti \
        -v /home/martin/git/go/src/github.com/monetas:/opt/go/src/github.com/monetas \
        -v $HOME:/home/dev \
        --name $CONTAINERID  \
        notary-dev bash -c "service supervisor start;sudo sh /opt/run_services.sh; cd
        $GOPATH/src/github.com/monetas/gotary/scripts/database && sh install.sh ; sleep 30000"
        sleep 3
fi

CMD="go test $@"
case $OPT in
        ("bash")
                CMD=bash
                ;;
        ("test")
                CMD="make tests"
                ;;
        ("db")
                CMD="make docker-dbcreate"
                ;;
        ("all")
                CMD="GOGC=off go install \$(scripts/our_packages.sh); GOGC=off go test \$(scripts/our_packages.sh)"
                ;;
        ("oldall")
                CMD="go test \$(scripts/our_packages.sh)"
                ;;
        ("vall")
                CMD="GOGC=off go install \$(scripts/our_packages.sh); GOGC=off go test -v \$(scripts/our_packages.sh)"
                ;;
        ("fall")
                CMD="GOGC=off go install \$(scripts/our_packages.sh); GOGC=off go test \$(scripts/our_packages.sh | grep $@ )"
                ;;

esac
#TODO add GOGC=off , better by 10s
# add go install
docker exec -ti $CONTAINERID bash -xc  "cd /opt/go/src/github.com/monetas/gotary; $CMD"
