#!/bin/sh
CONTAINERID=gotary-test

if [ $# -gt 0 ]; then
    OPT=$1
else
    OPT=test
fi

case $OPT in
    ("kill")
        docker kill $CONTAINERID
        docker rm $CONTAINERID
        exit
        ;;
esac

if ! docker ps | grep -q notary-dev; then
        echo "no running docker found, running new one"
        docker run  -p 2222:22 -d -ti \
        -v /home/martin/git/go/src/github.com/monetas:/opt/go/src/github.com/monetas \
        -v $HOME:/home/dev \
        --name $CONTAINERID  \
        notary-dev bash -c "sudo sh /opt/run_services.sh; cd $GOPATH/src/github.com/monetas/gotary/scripts/database && sh install.sh  ; sleep 3600"
        sleep 3
fi

CMD="go test $@"
case $OPT in
        ("bash")
                CMD=bash
                ;;
        ("test")
                CMD="make tests"
                ;;
        ("db")
                CMD="make docker-dbcreate"
                ;;
esac
docker exec -ti $CONTAINERID bash -c  "cd /opt/go/src/github.com/monetas/gotary; $CMD"
